### PR TITLE
Introduce parcel

### PR DESCRIPTION
**Pull request by EugenAz**

### CODE REVIEW

**Comment by FilipZafran** [comment]
Not sure how to check how the page looks now...

**Comment by FilipZafran** [comment]
I see the code changes, but is there a way to check how the page looks now with your changes, before Merging the pull... ?

**Comment by EugenAz** [comment]
Yes, sure. You have to pull the changes to your local repo. 
1. git fetch -p
2. git checkout introduce-parcel
3. npm install
4. npm start

**Comment by FilipZafran** [comment]
ok, why 3. npm install ? 
what do I install?

**Comment by FilipZafran** [comment]
actually not sure why we need npm as we are not using react ?

**Comment by EugenAz** [comment]
you will install all dependencies that are listed in the package.json.
See devDependencies and dependencies:
https://github.com/FilipZafran/FutsalCup/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20

**Comment by EugenAz** [comment]
not only react is stored in npm. but pretty much everything that is related to the front-end world. Tools, libraries, frameworks, utilities, code snippets, well it can be anything.

**Comment by FilipZafran** [comment]
ok, thx.
had no idea... I should pay you 6000eu for actually teaching me something... 

Ill stop for today so we can enjoy the evenings with our wifes. Have a good one! And not too much sex XD

**Pull request merged**
